#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NUnit.Tests.AndroidHelloTests.Resource", IsApplication=true)]

namespace NUnit.Tests.AndroidHelloTests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHello.Resource.String.app_name = global::NUnit.Tests.AndroidHelloTests.Resource.String.app_name;
			global::AndroidHello.Resource.String.hello = global::NUnit.Tests.AndroidHelloTests.Resource.String.hello;
			global::Nunit.Runner.Resource.String.ApplicationName = global::NUnit.Tests.AndroidHelloTests.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::NUnit.Tests.AndroidHelloTests.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::NUnit.Tests.AndroidHelloTests.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::NUnit.Tests.AndroidHelloTests.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::NUnit.Tests.AndroidHelloTests.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::NUnit.Tests.AndroidHelloTests.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020000
			public const int ApplicationName = 2130837504;
			
			// aapt resource value: 0x7F020002
			public const int app_name = 2130837506;
			
			// aapt resource value: 0x7F020001
			public const int Hello = 2130837505;
			
			// aapt resource value: 0x7F020003
			public const int hello = 2130837507;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
